name: Run Script1

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install requests
          python Dependabot_pull.py > depend.csv
      - uses: actions/upload-artifact@v2
        with: 
          name: Dependabot_CSV 
          path: depend.csv